# -*- coding: utf-8 -*-
"""phyllo_dipole

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-a6mKZUU0v-njr7Yo8FdS4i5YTETb7po
"""

#!/usr/bin/env python3
"""
PHYLLO V6.3: PRODUCTION SOLVER
Architecture: Implicit Navier-Stokes with Quantum-Informed Source Terms.
"""
import numpy as np
import matplotlib.pyplot as plt

class PhylloSolver:
    def __init__(self, nx=64, ny=64, nu=0.01):
        self.nx, self.ny = nx, ny
        self.nu = nu
        self.u, self.v = np.zeros((nx, ny)), np.zeros((nx, ny))
        self.p = np.zeros((nx, ny))
        self.dx = 1.0 / nx

    def get_quantum_force(self, i, j):
        # The Phyllo interaction potential
        center1, center2 = (25, 30), (40, 30)
        d1 = np.sqrt((i-center1[0])**2 + (j-center1[1])**2)
        d2 = np.sqrt((i-center2[0])**2 + (j-center2[1])**2)

        force = np.zeros(2)
        if d1 < 8: force += np.array([0.05, 0.05])
        if d2 < 8: force += np.array([-0.05, -0.05])
        return force

    def step(self, dt):
        # 1. Momentum Injection (Implicit-style)
        for i in range(1, self.nx-1):
            for j in range(1, self.ny-1):
                f = self.get_quantum_force(i, j)
                self.u[i, j] += dt * (f[0] + self.nu * 4)
                self.v[i, j] += dt * (f[1] + self.nu * 4)

        # 2. Pressure Projection (Maintain Incompressibility)
        for _ in range(20):
            self.p[1:-1, 1:-1] = 0.25 * (self.p[2:, 1:-1] + self.p[:-2, 1:-1] +
                                         self.p[1:-1, 2:] + self.p[1:-1, :-2])
        self.u[1:-1, 1:-1] -= 0.5 * (self.p[2:, 1:-1] - self.p[:-2, 1:-1]) / self.dx
        self.v[1:-1, 1:-1] -= 0.5 * (self.p[1:-1, 2:] - self.p[1:-1, :-2]) / self.dx

# Execution & Visualization
solver = PhylloSolver()
for _ in range(150): solver.step(0.005)
vort = np.gradient(solver.v, axis=0) - np.gradient(solver.u, axis=1)

plt.imshow(vort, cmap='RdBu_r'); plt.colorbar(); plt.show()