# -*- coding: utf-8 -*-
"""phyllo_fractal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GfOPeE_FTrHiR_x_KN1PRPpKHCpH7kdt
"""

#!/usr/bin/env python3
import numpy as np
import matplotlib.pyplot as plt

def get_sierpinski_mask(n):
    """Generates the fractal geometry mask."""
    mask = np.zeros((n, n))
    points = [(n//2, 0), (0, n-1), (n-1, n-1)]
    curr = (n//2, n//2)
    for _ in range(100000):
        target = points[np.random.randint(0, 3)]
        curr = ((curr[0] + target[0]) // 2, (curr[1] + target[1]) // 2)
        mask[curr[1], curr[0]] = 1
    return mask

class PhylloFractalSolver:
    def __init__(self, nx=256, ny=256, nu=0.0001):
        self.nx, self.ny = nx, ny
        self.nu = nu
        self.u, self.v = np.zeros((nx, ny)), np.zeros((nx, ny))
        self.p = np.zeros((nx, ny))
        self.dx = 1.0 / nx
        # Inject the fractal mask as a force field
        mask = get_sierpinski_mask(nx)
        self.f_field = np.stack([mask * 0.05, mask * 0.05])

    def step(self, dt):
        # Implicit-style Momentum + Fractal Force
        self.u += dt * (self.f_field[0] + self.nu * 4)
        self.v += dt * (self.f_field[1] + self.nu * 4)

        # Pressure Projection (Ensures Incompressibility)
        for _ in range(40):
            self.p[1:-1, 1:-1] = 0.25 * (self.p[2:, 1:-1] + self.p[:-2, 1:-1] +
                                         self.p[1:-1, 2:] + self.p[1:-1, :-2])
        self.u[1:-1, 1:-1] -= 0.5 * (self.p[2:, 1:-1] - self.p[:-2, 1:-1]) / self.dx
        self.v[1:-1, 1:-1] -= 0.5 * (self.p[1:-1, 2:] - self.p[1:-1, :-2]) / self.dx

# Run the long-duration simulation
solver = PhylloFractalSolver(256, 256)
for _ in range(1000): solver.step(0.005)

# Calculate and render the Vorticity Cascade
vort = np.gradient(solver.v, axis=0) - np.gradient(solver.u, axis=1)
plt.imshow(vort, cmap='magma')
plt.title("PHYLLO: Fractal Vortex Cascade")
plt.colorbar()
plt.show()