# -*- coding: utf-8 -*-
"""phyllo_assimilation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UCnMQopY3RRCOpE1ZxW_SqmuJYnBfQop
"""

#!/usr/bin/env python3
"""
PHYLLO V6.4: REAL-WORLD DATA ASSIMILATION
Architecture: Implicit Navier-Stokes with Sensor Data Forcing.
"""
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import griddata
import os

class PhylloSolver:
    def __init__(self, nx=64, ny=64, nu=0.01):
        self.nx, self.ny = nx, ny
        self.nu = nu
        self.u, self.v = np.zeros((nx, ny)), np.zeros((nx, ny))
        self.p = np.zeros((nx, ny))
        self.dx = 1.0 / nx
        # This will hold the continuous data mapped from our sparse sensors
        self.f_field = np.zeros((2, nx, ny))

    def load_real_world_data(self, filepath):
        """Loads sparse sensor data and interpolates it to the computational grid."""
        print(f"Loading sensor logs from {filepath}...")

        # Expected CSV format: [x_coord, y_coord, force_x, force_y]
        data = np.loadtxt(filepath, delimiter=',')
        points = data[:, 0:2]  # Sensor physical locations
        values = data[:, 2:4]  # Sensor readings (forces)

        # Create the dense grid coordinates for the solver
        grid_x, grid_y = np.mgrid[0:self.nx, 0:self.ny]

        # Interpolate the sparse points across the entire grid
        # We use 'cubic' interpolation to keep the fluid dynamics smooth
        mapped_fx = griddata(points, values[:, 0], (grid_x, grid_y), method='cubic', fill_value=0)
        mapped_fy = griddata(points, values[:, 1], (grid_x, grid_y), method='cubic', fill_value=0)

        self.f_field = np.stack([mapped_fx, mapped_fy])
        print("Data assimilation complete. Sensor field mapped to grid.")

    def step(self, dt):
        # 1. Vectorized Momentum Injection using the mapped real-world data
        self.u += dt * (self.f_field[0] + self.nu * 4)
        self.v += dt * (self.f_field[1] + self.nu * 4)

        # 2. Pressure Projection (Maintain Incompressibility)
        for _ in range(20):
            self.p[1:-1, 1:-1] = 0.25 * (self.p[2:, 1:-1] + self.p[:-2, 1:-1] +
                                         self.p[1:-1, 2:] + self.p[1:-1, :-2])
        self.u[1:-1, 1:-1] -= 0.5 * (self.p[2:, 1:-1] - self.p[:-2, 1:-1]) / self.dx
        self.v[1:-1, 1:-1] -= 0.5 * (self.p[1:-1, 2:] - self.p[1:-1, :-2]) / self.dx

# --- 1. SIMULATE REAL SENSOR DATA FOR TESTING (STRESS TEST) ---
# Generating 50 random sensors scattered across the 64x64 grid
num_sensors = 50
grid_size = 64

# Random X and Y coordinates (keeping them slightly away from the absolute edges)
sensor_x = np.random.uniform(5, grid_size - 5, num_sensors)
sensor_y = np.random.uniform(5, grid_size - 5, num_sensors)

# Random momentum vectors (fx, fy) to simulate chaotic, turbulent flow
force_x = np.random.uniform(-0.15, 0.15, num_sensors)
force_y = np.random.uniform(-0.15, 0.15, num_sensors)

# Stack into the expected CSV format: [x, y, fx, fy]
dummy_sensor_data = np.column_stack((sensor_x, sensor_y, force_x, force_y))

np.savetxt("sensor_log.csv", dummy_sensor_data, delimiter=",")
print(f"Generated {num_sensors} random sensor data points for stress test.")

# --- 2. EXECUTION & ASSIMILATION ---
solver = PhylloSolver(nx=64, ny=64)
solver.load_real_world_data("sensor_log.csv")

# Run the simulation using the sensor data
for _ in range(150):
    solver.step(0.005)

vort = np.gradient(solver.v, axis=0) - np.gradient(solver.u, axis=1)

# --- 3. VISUALIZATION ---
plt.imshow(vort, cmap='RdBu_r')
plt.title("PHYLLO: Real-World Data Assimilation")
plt.colorbar(label="Vorticity Intensity")
plt.show()